### PR TITLE
[IMP] Added template to generate XML of chart template

### PR DESCRIPTION
**Pull request by luistorresm**
In progress

### CODE REVIEW

**Comment by nhomar** [comment]
I will take care of this.

**Comment by moylop260** [comment]
FYI @alan196 sent me a library similar for CFDI.
They are receiving a json template to transform to XML.
We are receiving a dict template to transform to XML.
Here is the same good feature. (A dict or a json are similar)

I saw a difference they are using the original field names from original XML defined from SAT:
 - https://github.com/Paybook/sync-rest/blob/master/src/cfdi_structure.json

With this approach is easy to know the structure of the dictionary to receive because you have just a template.

But if you define a json or dict with custom fields to transform the XML then you need search the original field from XML SAT and search what is the custom field/key in the dict defined for that attribute.

custom_dict_key -> sat_xml_attribute

I mean, we have a template of the template.

Why not use directly the sat template like as `sat_dict_key -> sat_xml_attribute`?

**Comment by nhomar** [comment]
Why not use directly the sat template like as sat_dict_key -> sat_xml_attribute?


The main reason is that cfdilib is being designed to be used to ANY xml invoice from ANY xsd template then once we do "Perú" for example this will be irrelevant.

The other point is the lang itself, How do we explain the meaning in spanish of something that is pretty obvious in english to Belgian team for example?

- Then the reason 1 is English is more generic.
- The second one is the fact that CFDIv3.2 is only 1 of the versions of invoices we will be using.
- The template is the one that set those names the somebody can implement CFDIv32MINE and use another dict (it is 4 lines of code) and we can use it in another system or whatever with a new template called different.

I mean.... we will need always a process to transform from ODoo to A dict the values on that dict are not relevant the lang use nameA or NombreA will not save 1 line of code.

I hope you understand.

**Comment by moylop260** [comment]
If our standard will be use a template over other one, then we should use just one to show the message.

I mean, the message told us something about `LugarExpedicion` field (original template) but the data is showed with english template.

inv_2016_0003_-_odoo

IMHO We need show the data and the message with just one template to easy trace.

**Comment by nhomar** [comment]
On Fri, Nov 25, 2016 at 10:21 AM, moylop260 <notifications@github.com>
wrote:

> IMHO We need show the data and the message with just one template to easy
> trace.
>
>
I am not sure I understand the point?

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by nhomar** [comment]
BTW this PR was superseed previously we should argument this design topic in a separated issue.

**Pull request closed without merging**
