### PR TITLE
[FIX] cfdv32: The default Null value for cfdi is NA

### PR DESCRIPTION
**Pull request by moylop260**
Fix https://github.com/Vauxoo/mexico/issues/375

### CODE REVIEW

**Comment by moylop260** [comment]
```bash
> /home/travis/build/vauxoo-dev/cfdilib/tests/test_cfdilib.py(152)test_005_get_norfc()
-> self.assertTrue(invoice.ups.message.find('rfc') >= 0,

(Pdb) invoice.ups.message
u"Element '{http://www.sat.gob.mx/cfd/3}Comprobante', attribute 'NumCtaPago': [facet 'minLength'] The value '' has a length of '0'; this underruns the allowed minimum length of '4'."
```

screen shot 2016-11-12 at 12 48 10 pm

**Comment by nhomar** [comment]
@moylop260 I think this feature is fixed in the last version of the lib, due to the fact that if no account key in the dict simply the account will be removed from the xml.

Then, set via template is not necessary, but may be I miss something.

Regards.

**Comment by nhomar** [comment]
Look at this commit.

https://github.com/Vauxoo/cfdilib/commit/f27024c83833cd37c33a2b218d00cc104578e728

**Comment by moylop260** [comment]
Could you see the main comment of the issue related https://github.com/Vauxoo/mexico/issues/375 please?

**Comment by moylop260** [comment]
Fixed from odoo https://github.com/Vauxoo/mexico/pull/379

**Pull request closed without merging**
